# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ J2EE ]
  pull_request:
    branches: [ J2EE ]

jobs:
  securitytest:

    runs-on: ubuntu-latest
    name: decpcheck_test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Project With Maven
        run: mvn clean install
      - name: Depcheck
        uses: sonamsuragini-alt/jenkins-docker@J2EE
        id:  Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          others: ''
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
