# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ J2EE ]
  pull_request:
    branches: [ J2EE ]

jobs:
  securitytest:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: check out code
      
      - uses: sonamsuragini-alt/jenkins-docker@J2EE
        name: Build and Publish Docker image
        with:
          registry: github.io
          dockerfile: Dockerfile
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}} 
      - name: Depcheck
      
        uses: sonamsuragini-alt/jenkins-docker@J2EE
        id:  Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          others: ''
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
